"""Rasterize the rain glyphs (IPAGothic) and the terminal glyphs (VT323) into glyphs.h.

Embedding the glyphs as bitmaps means the screensaver looks the same on every
Windows install, whatever fonts it has.
Usage: python3 gen_glyphs.py <ipag.ttf> <VT323.ttf> <out glyphs.h>
"""
import sys
from PIL import Image, ImageDraw, ImageFont, ImageOps

RAIN = 'ｦｱｳｴｵｶｷｹｺｻｼｽｾｿﾀﾂﾃﾅﾆﾇﾈﾊﾋﾎﾏﾐﾑﾒﾓﾔﾕﾗﾘﾜ0123456789Z:・."=*+-<>¦｜'
CELL = 64
TERM_SIZE = 64


def rain_glyph(font, ch):
    img = Image.new('L', (CELL, CELL), 0)
    d = ImageDraw.Draw(img)
    w = font.getlength(ch)
    d.text(((CELL - w) / 2, 1), ch, font=font, fill=255)
    if ord(ch) > 0xFF:  # katakana and full-width marks are drawn mirrored, as in the film
        img = ImageOps.mirror(img)
    return img


def emit(name, imgs, w, h):
    out = [f'static const unsigned char {name}[{len(imgs)}][{w * h}] = {{']
    for img in imgs:
        data = img.tobytes()
        out.append('{' + ','.join(str(b) for b in data) + '},')
    out.append('};')
    return '\n'.join(out)


def main(ipag, vt323, dst):
    rf = ImageFont.truetype(ipag, 60)
    rain = [rain_glyph(rf, ch) for ch in RAIN]

    tf = ImageFont.truetype(vt323, TERM_SIZE)
    asc, desc = tf.getmetrics()
    tw, th = 26, asc + desc
    term = []
    for code in range(32, 127):
        img = Image.new('L', (tw, th), 0)
        ImageDraw.Draw(img).text((0, 0), chr(code), font=tf, fill=255)
        term.append(img)

    with open(dst, 'w') as f:
        f.write('// Generated by tools/gen_glyphs.py. Do not edit.\n#pragma once\n')
        f.write(f'enum {{ RAIN_COUNT = {len(rain)}, RAIN_CELL = {CELL}, TERM_W = {tw}, TERM_H = {th}, '
                f'TERM_BASE = {TERM_SIZE}, TERM_FIRST = 32, TERM_COUNT = {len(term)} }};\n')
        f.write(f'static const double TERM_ADVANCE = {tf.getlength("W"):.4f};\n')
        f.write(emit('RAIN_GLYPHS', rain, CELL, CELL) + '\n')
        f.write(emit('TERM_GLYPHS', term, tw, th) + '\n')


if __name__ == '__main__':
    main(*sys.argv[1:4])
